project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    comments:
      hypothesis: true
    code-fold: true
  pdf:
    link-citations: true
    pdf-engine: xelatex


execute:
  freeze: true
